version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6136:4173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      # - VITE_API_URL=https://mommynme.onrender.com/api
      - NODE_ENV=development
    command: >
      sh -c "npm run build && npm run dev"
    restart: unless-stopped
